name: CI with Docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
jobs:
  build:
    # Skip workflow if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Increment Version
      run: |
        # Extract current version
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $CURRENT_VERSION"

        # Increment patch version using sed
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

        # If PATCH is empty, set it to 0 (handles 2-part versions like 1.0)
        if [ -z "$PATCH" ]; then
          PATCH=0
          NEW_PATCH=1
        else
          NEW_PATCH=$((PATCH + 1))
        fi

        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "New version: $NEW_VERSION"

        # Update version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false

        # Commit and push the version change
        git add pom.xml
        git commit -m "Bump version to $NEW_VERSION [skip ci]"
        git push https://${{ github.token }}@github.com/${{ github.repository }}.git HEAD:main

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
  #docker:
   # needs: build
    #runs-on: ubuntu-latest
    #steps:
     # - name: Checkout Code
      #  uses: actions/checkout@v4

#      - name: Set up Docker Buildx
 #       uses: docker/setup-buildx-action@v2

  #    - name: Log in to Docker Hub
   #     uses: docker/login-action@v2
    #    with:
     #     username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build and Push Docker Image
      #  run: |
       #   docker build -t your-dockerhub-username/${{ github.event.repository.name }}:${{ github.sha }} -f Dockerfile .
        #  docker push your-dockerhub-username/${{ github.event.repository.name }}:${{ github.sha }}
