name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR File
        run: |
          mvn clean package

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/${{ github.event.repository.name }} .
          docker push your-dockerhub-username/${{ github.event.repository.name }}
